- name: Expense project- Backend
  hosts: all
  become: true
  vars:
    component: backend
  tasks:
    - name: Copy Backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Diasble nodejs module
      ansible.builtin.shell: yum module disable nodejs -y

    - name: Enable nodejs18
      ansible.builtin.shell: yum module enable nodejs:18 -y

#    - name: Install NodeJS Repos
#      ansible.builtin.shell: -sL https://rpm.nodesource.com/setup_lts.x

    - name: Install NodeJS
      ansible.builtin.yum:
        name: nodejs
        state: installed

    - name: Add Application User
      ansible.builtin.user:
        name: expense

    - name: Clean Old content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create App Directory
      ansible.builtin.file:
        path:  /app
        state: directory

    - name: Download & Extract Backend Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Download NodeJS Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: install mysql client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.manasareddy.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

    - name: Systemd-Setup
      ansible.builtin.import_tasks: systemd-setup.yml
