- name: MYSQL Setup
  hosts: all
  become: true
  vars:
    component: mysqld
  tasks:
    - name: Copy MySQL Repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Disable MySQL 8 version
      ansible.builtin.shell: yum module disable mysql -y

    - name: Install MySQL Server
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: Systemd-Setup
      ansible.builtin.import_tasks: systemd-setup.yml

    - name: Set Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1